# .github/workflows/deploy.yml

name: Deploy React + Vite to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Job for building and deploying the site
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js with the correct version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies using npm or yarn
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project for production
      - name: Build the project
        run: npm run build

      # Step 5: Upload the built site as an artifact (GitHub Pages deploys from this)
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist # Vite output directory

  # Deployment job to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
